run:
  skip-files:
    - sql/bindata.go
    - omnibus-adminui

linters:
  enable:
    - bodyclose
    - goimports
    - misspell
  disable:
    - gochecknoglobals
    - lll
    - maligned
    - prealloc
    - typecheck
    - unused

linters-settings:
  errcheck:
    ignore: fmt:.*,io:WriteString
