---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitserver-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: moblog-repositories-nfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitserver
spec:
  selector:
    matchLabels:
      app: gitserver
  replicas: 2
  template:
    metadata:
      labels:
        app: gitserver
    spec:
      containers:
      - name: gitserver
        image: moblog-cloud/gitserver:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis_url
        command: [
          '/home/gitserver/gitserver',
          '-listen', '0.0.0.0:8080',
          '-adminServer', 'http://$(ADMINSERVER_SERVICE_NAME)/api',
          '-repositoryBase', '/repositories',
          '-redisJobQueue', '$(REDIS_URL)'
        ]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: git-repositories
          mountPath: /repositories
      volumes:
      - name: git-repositories
        persistentVolumeClaim:
          claimName: gitserver-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gitserver
  labels:
    app: gitserver
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gitserver
